### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by Loewe1000** [johannes-wolf/typst-plot#2]
If I try to compile the examples with typst 0.1.0, I get the following errors:

error: expected identifier
    ┌─ ../plot.typ:145:9
    │
145 │       for (name, r) in computed-range {
    │          ^

help: error occurred while importing this module
  ┌─ simple.typ:1:8
  │
1 │ #import "../plot.typ": plot
  │         ^^^^^^^^^^^^^

error: expected identifier
    ┌─ ../plot.typ:159:7
    │
159 │     for (name, t) in tics {
    │        ^

**Comment by johannes-wolf** [comment]
The latest commits include changes to compile with typst `main` branch.
You can try commit `1b787c5d4ab5f9bf17247fbbeed84176cf69fc7a`, which should work with typst 0.1.0. There was a breaking change in how for loops over dictionaries work, hence the incompatibility. :(

**Comment by tiger2005** [comment]
Change `for (name, r) in dict` to `for name, r in dict` works for me. Maybe the feature is changed in Typst 0.1.0.

**Comment by johannes-wolf** [comment]
> Change `for (name, r) in dict` to `for name, r in dict` works for me. Maybe the feature is changed in Typst 0.1.0.

Yes, the unpacking behaviour changed with typst commit https://github.com/typst/typst/commit/0f8219b392e96d3cf7d784ee5d474274169d9918.

**Comment by johannes-wolf** [comment]
Typst version released today includes the new `let` binding syntax.
