### ISSUE TITLE
Region plots?

### ISSUE THREAD

**Issue by Kreijstal** [johannes-wolf/typst-plot#3]
any way of doing region plots? o.o

**Comment by johannes-wolf** [comment]
Currently not. Can you give an example of a plot?
Plan is to move this libraries implementation over to `typst-canvas`, which would make it way simpler to add new plot types.

**Comment by Kreijstal** [comment]
the epigraph of any function, for example

**Comment by johannes-wolf** [comment]
Hi, I have implemented plotting in my other library `CeTZ` (formerly `typst-canvas`).
With that library you can draw the epigraph or hypograph of a function.
The PR is not yet merged, have a look here:
https://github.com/johannes-wolf/typst-canvas/tree/plotting-lib and/or https://github.com/johannes-wolf/typst-canvas/pull/92
