### ISSUE TITLE
Having to many tics blocks very long -> forever

### ISSUE THREAD

**Issue by linuxrider** [johannes-wolf/typst-plot#7]
I like the ability to quickly plot something in typst. Thank you for the work.

When you put too many tics execution takes very long. Even leaving the document and going to the dashboard in the webapp does not stop the execution. 
This happened by accident to me several times.
I have simply copied typst-plot into the document.

```
#import "plot.typ": plot
#import "plot-sample.typ": *
#plot(
  y-tics: (every:0.00001 ),
  (data:  sample(x => x)),
)
```

**Comment by johannes-wolf** [comment]
Thank you for the bug report. With commit e5251f6 plotting will fail if more than 100 tics are generated using the `every` field.
