### ISSUE TITLE
Standard Arrow Plots?

### ISSUE THREAD

**Issue by riccardostokker** [johannes-wolf/typst-plot#8]
Is there any way of plotting a more standard-looking plot like this?

![image](https://github.com/johannes-wolf/typst-plot/assets/62010554/d6610ee1-ca20-442b-be2f-919afb14774c)

Thank you,
Riccardo

**Comment by johannes-wolf** [comment]
Hello,
I have added a plotting implementation to my other library "CeTZ" (formerly `typst-canvas`), that supports this style of plots.

It is not yet released and is missing the "mark" feature. You can have a look here: https://github.com/johannes-wolf/typst-canvas/pull/92

I will change this library to use CeTZ and its plotting implementation internally soon, which will bring lots of other features.

Example:
![grafik](https://github.com/johannes-wolf/typst-plot/assets/519002/bb2e33ee-d1c2-4fef-8d05-ead1581afe8c)

**Comment by johannes-wolf** [comment]
I have merged the feature to CeTZ. See: https://github.com/johannes-wolf/typst-canvas for the new API. This package will not receive new features (as of now).
